//! Interactive `abe init` wizard: ask how many models, collect each model's
//! details (OpenAI / Anthropic / OpenAI-compatible URL / CLI), and write a
//! config YAML. Lives in the binary (not install.sh) because `curl | sh` can't
//! read interactive input — stdin is the piped script.

use crate::config::Defaults;
use anyhow::{Context, Result};
use std::io::{BufRead, Write};

/// One model's collected answers. `kind` is the YAML value
/// (openai | anthropic | openai-compatible | cli).
pub struct ModelSpec {
    pub name: String,
    pub kind: String,
    pub model: Option<String>,
    pub base_url: Option<String>,
    pub api_key_env: Option<String>,
    pub cli: Option<String>,
    pub fast: bool,
}

/// Render a clean config YAML from collected specs. Pure — the unit test parses
/// its output back through `Config::from_yaml` to guarantee validity.
pub fn render_yaml(
    models: &[ModelSpec],
    defaults: &Defaults,
    rounds: u32,
    protocol: &str,
    chairman: Option<&str>,
) -> String {
    let mut s = format!(
        "# Generated by `abe init`.\ndefaults:\n  temperature: {}\n  max_tokens: {}\n  timeout_secs: {}\n  retries: {}\n  max_context_kb: {}\n\nmodels:\n",
        defaults.temperature,
        defaults.max_tokens,
        defaults.timeout_secs,
        defaults.retries,
        defaults.max_context_kb,
    );
    for m in models {
        let mut parts = vec![format!("name: {}", m.name), format!("kind: {}", m.kind)];
        match m.kind.as_str() {
            "cli" => {
                if let Some(c) = &m.cli {
                    parts.push(format!("cli: {c}"));
                }
                if let Some(x) = &m.model {
                    parts.push(format!("model: \"{x}\""));
                }
                if m.fast {
                    parts.push("fast: true".into());
                }
            }
            "openai-compatible" => {
                if let Some(x) = &m.model {
                    parts.push(format!("model: \"{x}\""));
                }
                if let Some(u) = &m.base_url {
                    parts.push(format!("base_url: \"{u}\""));
                }
                if let Some(k) = m.api_key_env.as_deref().filter(|k| !k.is_empty()) {
                    parts.push(format!("api_key_env: {k}"));
                }
            }
            _ => {
                if let Some(x) = &m.model {
                    parts.push(format!("model: {x}"));
                }
                if let Some(k) = m.api_key_env.as_deref().filter(|k| !k.is_empty()) {
                    parts.push(format!("api_key_env: {k}"));
                }
            }
        }
        s.push_str(&format!("  - {{ {} }}\n", parts.join(", ")));
    }
    s.push_str(&format!(
        "\ndebate:\n  rounds: {rounds}\n  protocol: {protocol}\n  anonymize: true\n"
    ));
    if let Some(c) = chairman.filter(|c| !c.is_empty()) {
        s.push_str(&format!("  chairman: {c}\n"));
    }
    if let Some(first) = models.first() {
        s.push_str(&format!("\nvalidate:\n  reviewers: [{}]\n", first.name));
    }
    s
}

/// Run the interactive wizard against stdin, write the YAML to the chosen path.
pub async fn run() -> Result<()> {
    let stdin = std::io::stdin();
    let mut r = stdin.lock();
    println!("abe init — let's build your config.\n");

    let n: usize = loop {
        let a = prompt(&mut r, "How many models? (1-5)", Some("2"))?;
        match a.parse::<usize>() {
            Ok(v) if (1..=5).contains(&v) => break v,
            _ => println!("  please enter a number from 1 to 5"),
        }
    };

    let mut models = Vec::with_capacity(n);
    for i in 1..=n {
        println!("\n--- model {i} of {n} ---");
        let spec = prompt_model(&mut r, i).await?;
        models.push(spec);
    }

    let defaults = prompt_defaults(&mut r)?;

    println!("\n--- debate settings ---");
    let rounds: u32 = prompt(&mut r, "Critique rounds (0 = broadcast only)", Some("1"))?
        .parse()
        .unwrap_or(1);
    let protocol = loop {
        let p = prompt(&mut r, "Protocol (synthesis/majority/judge)", Some("synthesis"))?;
        if ["synthesis", "majority", "judge"].contains(&p.as_str()) {
            break p;
        }
        println!("  choose synthesis, majority, or judge");
    };
    let chairman = if matches!(protocol.as_str(), "synthesis" | "judge") {
        let names: Vec<&str> = models.iter().map(|m| m.name.as_str()).collect();
        let c = prompt(
            &mut r,
            &format!("Chairman model for {protocol} ({})", names.join("/")),
            models.first().map(|m| m.name.as_str()),
        )?;
        Some(c)
    } else {
        None
    };

    let yaml = render_yaml(&models, &defaults, rounds, &protocol, chairman.as_deref());

    let default_path = default_config_path();
    let path = prompt(&mut r, "Write config to", Some(&default_path))?;
    let path = expand_tilde(&path);
    if std::path::Path::new(&path).exists() {
        let ow = prompt(&mut r, &format!("{path} exists — overwrite? (y/N)"), Some("N"))?;
        if !ow.eq_ignore_ascii_case("y") {
            println!("aborted; here is the config so you can save it yourself:\n\n{yaml}");
            return Ok(());
        }
    }
    if let Some(parent) = std::path::Path::new(&path).parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(&path, &yaml).with_context(|| format!("writing {path}"))?;
    println!("\nwrote {path}\nrun:  abe models   # to check reachability\nthen: abe debate \"your question\"");
    Ok(())
}

async fn prompt_model(r: &mut impl BufRead, i: usize) -> Result<ModelSpec> {
    let name = prompt(r, "Name (e.g. gpt, claude, local)", Some(&format!("m{i}")))?;
    println!("  Type:  1) OpenAI   2) Anthropic   3) OpenAI-compatible URL (local/vLLM/Ollama)   4) CLI (codex/claude/opencode)");
    let kind_choice = loop {
        let c = prompt(r, "  Choose 1-4", Some("1"))?;
        match c.as_str() {
            "1" | "2" | "3" | "4" => break c,
            _ => println!("    enter 1, 2, 3, or 4"),
        }
    };
    let mut spec = ModelSpec {
        name,
        kind: String::new(),
        model: None,
        base_url: None,
        api_key_env: None,
        cli: None,
        fast: false,
    };
    match kind_choice.as_str() {
        "1" => {
            spec.kind = "openai".into();
            let env = prompt(r, "  API key env var", Some("OPENAI_API_KEY"))?;
            let key = std::env::var(&env).ok();
            spec.api_key_env = Some(env);
            spec.model =
                Some(choose_model(r, "https://api.openai.com/v1", key.as_deref(), Some("gpt-5.5"), true).await?);
        }
        "2" => {
            spec.kind = "anthropic".into();
            // Anthropic's models endpoint uses different auth headers; keep a typed default.
            spec.model = Some(prompt(r, "  Model id", Some("claude-opus-4-8"))?);
            spec.api_key_env = Some(prompt(r, "  API key env var", Some("ANTHROPIC_API_KEY"))?);
        }
        "3" => {
            spec.kind = "openai-compatible".into();
            let base = prompt(r, "  Base URL", Some("http://192.168.1.10:8000/v1"))?;
            let env = prompt(r, "  API key env var (blank = no auth)", Some(""))?;
            let key = if env.is_empty() { None } else { std::env::var(&env).ok() };
            spec.api_key_env = if env.is_empty() { None } else { Some(env) };
            spec.model = Some(choose_model(r, &base, key.as_deref(), None, false).await?);
            spec.base_url = Some(base);
        }
        _ => {
            spec.kind = "cli".into();
            let cli = loop {
                let c = prompt(r, "  Which CLI (codex/claude/opencode)", Some("codex"))?;
                if ["codex", "claude", "opencode"].contains(&c.as_str()) {
                    break c;
                }
                println!("    choose codex, claude, or opencode");
            };
            spec.cli = Some(cli.clone());
            // opencode requires an explicit provider/model; codex/claude can use
            // the account default (blank).
            if cli == "opencode" {
                spec.model = Some(loop {
                    let v = prompt(r, "  Model (provider/model — required for opencode)", None)?;
                    if !v.is_empty() {
                        break v;
                    }
                    println!("    opencode needs a model, e.g. ollama/llama3.1 or openai/gpt-5.5");
                });
            } else {
                let m = prompt(r, "  Model (blank = the CLI's default account model)", Some(""))?;
                spec.model = if m.is_empty() { None } else { Some(m) };
            }
            spec.fast = prompt(r, "  Fast mode? (y/N)", Some("N"))?.eq_ignore_ascii_case("y");
        }
    }
    Ok(spec)
}

/// Offer to fetch the endpoint's model list and let the user pick by number.
/// Falls back to manual entry on decline / failure / empty list. `filter_chat`
/// trims a long OpenAI list to chat-ish ids (gpt*/o*). Always returns non-empty.
async fn choose_model(
    r: &mut impl BufRead,
    base_url: &str,
    api_key: Option<&str>,
    default: Option<&str>,
    filter_chat: bool,
) -> Result<String> {
    let offer = prompt(r, "  Fetch available models from the endpoint? (Y/n)", Some("Y"))?;
    if !offer.eq_ignore_ascii_case("n") {
        match fetch_models(base_url, api_key).await {
            Ok(ids) if !ids.is_empty() => {
                let ids = filter_sort(ids, filter_chat);
                println!("  available models:");
                for (j, m) in ids.iter().enumerate() {
                    println!("    {}) {}", j + 1, m);
                }
                loop {
                    let pick = prompt(r, "  Pick a number, or type a model id", default)?;
                    if let Ok(idx) = pick.parse::<usize>() {
                        if (1..=ids.len()).contains(&idx) {
                            return Ok(ids[idx - 1].clone());
                        }
                        println!("    out of range (1-{})", ids.len());
                        continue;
                    }
                    if !pick.is_empty() {
                        return Ok(pick);
                    }
                    if let Some(d) = default {
                        return Ok(d.to_string());
                    }
                    println!("    enter a number or a model id");
                }
            }
            Ok(_) => println!("  (endpoint returned no models — enter manually)"),
            Err(e) => println!("  (couldn't fetch models: {e} — enter manually)"),
        }
    }
    // manual fallback (model id is required)
    loop {
        let m = prompt(r, "  Model id", default)?;
        if !m.is_empty() {
            return Ok(m);
        }
        println!("    a model id is required");
    }
}

fn filter_sort(ids: Vec<String>, filter_chat: bool) -> Vec<String> {
    let mut ids = if filter_chat {
        let chat: Vec<String> = ids
            .iter()
            .filter(|m| m.starts_with("gpt") || m.starts_with('o'))
            .cloned()
            .collect();
        if chat.is_empty() {
            ids
        } else {
            chat
        }
    } else {
        ids
    };
    ids.sort();
    ids
}

/// GET `{base_url}/models` and return the `data[].id` values. Works for OpenAI
/// (Bearer key) and OpenAI-compatible servers (vLLM/Ollama/LM Studio, often no auth).
async fn fetch_models(base_url: &str, api_key: Option<&str>) -> Result<Vec<String>> {
    let url = format!("{}/models", base_url.trim_end_matches('/'));
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()?;
    let mut req = client.get(&url);
    if let Some(k) = api_key.filter(|k| !k.is_empty()) {
        req = req.bearer_auth(k);
    }
    let resp = req.send().await.with_context(|| format!("GET {url}"))?;
    if !resp.status().is_success() {
        anyhow::bail!("{url} returned {}", resp.status());
    }
    let body: serde_json::Value = resp.json().await.context("parsing models response")?;
    let ids = body
        .get("data")
        .and_then(|d| d.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|m| m.get("id").and_then(|x| x.as_str()).map(String::from))
                .collect()
        })
        .unwrap_or_default();
    Ok(ids)
}

/// Offer to customize the `defaults` block. Pressing N (or enter) keeps the
/// engine's built-in defaults; otherwise each field is pre-filled with its
/// current default so Enter accepts it.
fn prompt_defaults(r: &mut impl BufRead) -> Result<Defaults> {
    let d = Defaults::default();
    let customize = prompt(r, "\nCustomize defaults (temperature, tokens, timeouts)? (y/N)", Some("N"))?;
    if !customize.eq_ignore_ascii_case("y") {
        return Ok(d);
    }
    let temperature = prompt(r, "  Temperature", Some(&d.temperature.to_string()))?
        .parse()
        .unwrap_or(d.temperature);
    let max_tokens = prompt(r, "  Max tokens per answer", Some(&d.max_tokens.to_string()))?
        .parse()
        .unwrap_or(d.max_tokens);
    let timeout_secs = prompt(r, "  Timeout (seconds)", Some(&d.timeout_secs.to_string()))?
        .parse()
        .unwrap_or(d.timeout_secs);
    let retries = prompt(r, "  Retries (HTTP providers)", Some(&d.retries.to_string()))?
        .parse()
        .unwrap_or(d.retries);
    let max_context_kb = prompt(r, "  Max context KB (warn above)", Some(&d.max_context_kb.to_string()))?
        .parse()
        .unwrap_or(d.max_context_kb);
    Ok(Defaults {
        temperature,
        max_tokens,
        timeout_secs,
        retries,
        max_context_kb,
    })
}

/// Print a prompt with an optional default and read one trimmed line. Empty
/// input returns the default (or "").
fn prompt(r: &mut impl BufRead, msg: &str, default: Option<&str>) -> Result<String> {
    match default {
        Some(d) if !d.is_empty() => print!("{msg} [{d}]: "),
        _ => print!("{msg}: "),
    }
    std::io::stdout().flush()?;
    let mut line = String::new();
    r.read_line(&mut line)?;
    let v = line.trim();
    Ok(if v.is_empty() {
        default.unwrap_or("").to_string()
    } else {
        v.to_string()
    })
}

fn default_config_path() -> String {
    match std::env::var("XDG_CONFIG_HOME").ok().filter(|s| !s.is_empty()) {
        Some(x) => format!("{x}/abe/config.yaml"),
        None => "~/.config/abe/config.yaml".to_string(),
    }
}

fn expand_tilde(path: &str) -> String {
    match path.strip_prefix("~/") {
        Some(rest) => match std::env::var("HOME") {
            Ok(home) => format!("{home}/{rest}"),
            Err(_) => path.to_string(),
        },
        None => path.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    #[test]
    fn rendered_yaml_round_trips_through_config_parser() {
        let models = vec![
            ModelSpec {
                name: "gpt".into(),
                kind: "openai".into(),
                model: Some("gpt-5.1".into()),
                base_url: None,
                api_key_env: Some("OPENAI_API_KEY".into()),
                cli: None,
                fast: false,
            },
            ModelSpec {
                name: "local".into(),
                kind: "openai-compatible".into(),
                model: Some("qwen3".into()),
                base_url: Some("http://192.168.1.10:8000/v1".into()),
                api_key_env: None,
                cli: None,
                fast: false,
            },
            ModelSpec {
                name: "cx".into(),
                kind: "cli".into(),
                model: Some("ollama/llama3.1".into()),
                base_url: None,
                api_key_env: None,
                cli: Some("opencode".into()),
                fast: true,
            },
        ];
        let defaults = Defaults {
            max_tokens: 2048,
            ..Defaults::default()
        };
        let yaml = render_yaml(&models, &defaults, 1, "synthesis", Some("gpt"));
        let cfg = Config::from_yaml(&yaml).expect("generated YAML must parse");
        assert_eq!(cfg.models.len(), 3);
        assert_eq!(cfg.models[0].name, "gpt");
        assert_eq!(cfg.models[1].base_url.as_deref(), Some("http://192.168.1.10:8000/v1"));
        assert!(cfg.models[2].fast);
        assert_eq!(cfg.models[2].model.as_deref(), Some("ollama/llama3.1"), "cli model must round-trip");
        assert_eq!(cfg.defaults.max_tokens, 2048, "customized default must round-trip");
        assert_eq!(cfg.debate.rounds, 1);
        assert_eq!(cfg.debate.chairman.as_deref(), Some("gpt"));
        assert_eq!(cfg.validate.reviewers, vec!["gpt"]);
    }
}
